version: 0.2

env:
  variables:
    BUILD_PREFIX: "ahorro-ui/android"

phases:
  install:
    runtime-versions:
      golang: 1.23
    commands:
      - echo Installing dependencies...
      - go version
      - make --version
  build:
    commands:
      - echo Building Go microservice...
      - make upload-and-tag
artifacts:
  files:
    - build/service-handler/transactions-lambda.zip
